### ISSUE TITLE
NullPointerException in Logging

### ISSUE THREAD

**Issue by fbausch** [MarkusH/pxchat#12]
When you try to log in with wrong password the following problem occurs:

pxchat.net.Client$1@57e787> Client disconnected
java.lang.NullPointerException
    at pxchat.util.Logging.endLog(Logging.java:86)
    at pxchat.gui.ClientMain$8.clientDisconnect(ClientMain.java:309)
    at pxchat.net.Client$1.clientDisconnect(Client.java:133)
    at pxchat.net.tcp.CustomSocket.doDisconnect(CustomSocket.java:165)
    at pxchat.net.tcp.CustomSocket.readCallback(CustomSocket.java:214)
    at pxchat.net.tcp.CustomSocket.access$4(CustomSocket.java:204)
    at pxchat.net.tcp.CustomSocket$ReadThread.run(CustomSocket.java:41)

**Comment by MarkusH** [comment]
fix NullPointerException when disconnecting with wrong credentials.
closed by 770e5aead2235f73f897e2ed16a186decdd54546
