### ISSUE TITLE
An error ocurred loading the config file

### ISSUE THREAD

**Issue by MarkusH** [MarkusH/pxchat#19]
$ java -version

openjdk6 6.b20_1.9.4-1

An error ocurred loading the config file
Uncaught error fetching image:
java.lang.ArrayIndexOutOfBoundsException
at java.lang.System.arraycopy(Native Method)
at sun.awt.image.PNGFilterInputStream.read(PNGImageDecoder.java:828)
at java.util.zip.InflaterInputStream.fill(InflaterInputStream.java:238)
at java.util.zip.InflaterInputStream.read(InflaterInputStream.java:158)
at java.io.BufferedInputStream.fill(BufferedInputStream.java:235)
at java.io.BufferedInputStream.read1(BufferedInputStream.java:275)
at java.io.BufferedInputStream.read(BufferedInputStream.java:334)
at sun.awt.image.PNGImageDecoder.produceImage(PNGImageDecoder.java:364)
at sun.awt.image.InputStreamImageSource.doFetch(InputStreamImageSource.java:264)
at sun.awt.image.ImageFetcher.fetchloop(ImageFetcher.java:189)
at sun.awt.image.ImageFetcher.run(ImageFetcher.java:153)
Exception in thread "main" java.lang.NullPointerException
at pxchat.gui.I18n.getLanguages(I18n.java:178)
at pxchat.gui.ClientMain.<init>(ClientMain.java:185)
at pxchat.gui.ClientMain.main(ClientMain.java:62)

**Comment by markusd** [comment]
Fixed
