### ISSUE TITLE
[Server] Win client cannot connect to server

### ISSUE THREAD

**Issue by fbausch** [MarkusH/pxchat#20]
When trying to log in to a chat I get this exception in the server:

pxchat.net.Server$1@b64435> new connection pxchat.net.tcp.CustomSocket@37fb1e --> pxchat.net.protocol.core.AuthFrameAdapter@1bfc93a
Connected users: {}
pxchat.net.Server$1@b64435> Client with id 1 disconnected.
java.net.SocketException: Socket closed
    at java.net.SocketOutputStream.socketWrite(SocketOutputStream.java:116)
    at java.net.SocketOutputStream.write(SocketOutputStream.java:141)
    at javax.crypto.CipherOutputStream.write(CipherOutputStream.java:157)
    at java.io.ObjectOutputStream$BlockDataOutputStream.drain(ObjectOutputStream.java:1857)
    at java.io.ObjectOutputStream$BlockDataOutputStream.setBlockDataMode(ObjectOutputStream.java:1766)
    at java.io.ObjectOutputStream.writeNonProxyDesc(ObjectOutputStream.java:1273)
    at java.io.ObjectOutputStream.writeClassDesc(ObjectOutputStream.java:1227)
    at java.io.ObjectOutputStream.writeOrdinaryObject(ObjectOutputStream.java:1411)
    at java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1174)
    at java.io.ObjectOutputStream.writeFatalException(ObjectOutputStream.java:1557)
    at java.io.ObjectOutputStream.writeObject(ObjectOutputStream.java:349)
    at pxchat.net.tcp.CustomSocket$WriteThread.run(CustomSocket.java:83)

**Comment by fbausch** [comment]
java -version:
1.6.0_23

**Comment by markusd** [comment]
Can somebody verify that?

**Comment by markusd** [comment]
Well, thats ridiculous. Image me and Markus searching this bug for about 12 hours in order to meet the deadline and at last - finding the bug in some code nobody would think about: YOURS. I can't even begin to describe how much you have failed. The code you wrote to scroll the chat log causes Windows clients to disconnect, just wonderful. Nobody would have been able to do that.... except you.

**Comment by MarkusH** [comment]
Yes we can! And we can proudly present the waste producer: Mr. fbausch!

Mr. fbausch, have you ever thought about your changes in c433144a8ab304523f36318bc5cb133de614e392?
Mr. fbausch, have you ever thought about what would happen if this does NOT work?
Mr. fbausch, have you ever thought about fixing bugs instead of producing new?

The traceback from top and this one should help you to fix the bug: http://paste.pocoo.org/show/328307/

As a hint: put the new scrolling method into a try-except block and use the old one as a fall-back in except!

**Comment by fbausch** [comment]
I'm so sorry, shame on me… I hope my commit fixes that ****.

Please test it!
